// Campaign photography is illustrative; the club gallery remains entirely factual.
export function applyCampaign(content, {tag, btn, photo, maps, cta}) {
  const campaignPhoto = (file, alt, cls = '') => `<img class="${cls}" src="/assets/${file}" alt="${alt} — AI-generated campaign image" width="1200" height="1500" loading="lazy" decoding="async">`;
  const programs = () => `<div class="program-grid">
    <a class="program-card reveal" href="/training/#strength"><div class="program-image">${campaignPhoto('campaign-detail.webp','Chalked hands holding a barbell')}<span class="program-number">01</span><span class="image-credit">AI campaign</span></div><div class="program-copy"><span class="card-index">STRENGTH</span><h3>Find your strong.</h3><p>Free weights, focused reps, and a foundation to build on.</p><span class="program-link">Explore strength</span></div></a>
    <a class="program-card reveal" href="/training/#conditioning"><div class="program-image">${campaignPhoto('campaign-energy.webp','Athlete holding dumbbells')}<span class="program-number">02</span><span class="image-credit">AI campaign</span></div><div class="program-copy"><span class="card-index">CONDITIONING</span><h3>Bring the energy.</h3><p>Build a routine for your stamina, movement, and everyday life.</p><span class="program-link">Explore conditioning</span></div></a>
    <a class="program-card reveal" href="/training/#guidance"><div class="program-image">${photo('free-weights.jpg','Actual free weights and blue training turf at Kulture Fitness Club')}<span class="program-number">03</span><span class="image-credit">Inside Kulture</span></div><div class="program-copy"><span class="card-index">YOUR STARTING POINT</span><h3>Make it yours.</h3><p>A first session or a fresh start. Find your place on the floor.</p><span class="program-link">Find your approach</span></div></a>
  </div>`;

  content.home = () => `<section class="hero campaign-hero" aria-labelledby="hero-title">
    <img class="hero-photo" src="/assets/campaign-strength.webp" alt="Athlete preparing with chalk before a workout — AI-generated Kulture campaign" fetchpriority="high" width="1536" height="1024">
    <div class="hero-shade"></div><div class="hero-content wrap">
      <p class="eyebrow hero-eyebrow"><span></span>KULTURE FITNESS CLUB <b>/</b> N3 CIDCO</p>
      <h1 id="hero-title"><span>MAKE</span><span>STRONG</span><em>A HABIT.</em></h1>
      <p>Your next chapter starts with showing up.<br>Find your strength. Find your Kulture.</p>
      <div class="button-row">${btn('Request a trial','/contact/?interest=Trial%20visit')}${btn('Explore memberships','/memberships/','outline')}</div>
      <a class="hero-rating" href="${maps}" target="_blank" rel="noopener noreferrer"><span class="stars" aria-label="5 out of 5 stars">★★★★★</span><p><strong>5.0 on Google</strong><span>60 Google reviews</span></p></a>
    </div>
    <div class="hero-caption"><span>THE KULTURE MINDSET</span><strong>Earned.<br>Every day.</strong><small>AI-generated campaign</small></div>
    <div class="hero-bottom wrap"><a href="#discover" class="hero-explore">DISCOVER YOUR KULTURE <span aria-hidden="true">↓</span></a><span>CHHATRAPATI SAMBHAJINAGAR, MH</span></div>
  </section>
  <div class="discipline-strip"><div class="wrap"><span>SHOW UP.</span><i aria-hidden="true"></i><span>PUT IN THE WORK.</span><i aria-hidden="true"></i><span>COME BACK STRONGER.</span></div></div>
  <section class="wrap section" id="discover"><div class="section-heading reveal"><div>${tag('01 / FIND YOUR FOCUS')}<h2>Different goals.<br><em>One Kulture.</em></h2></div><p>First day or next milestone, there’s a place for you here. Train with intention, one session at a time.</p></div>${programs()}</section>
  <section class="story-section"><div class="wrap split"><div class="story-image reveal">${photo('strength-zone.jpg','Actual strength equipment at Kulture Fitness Club')}<div class="image-label"><span>INSIDE KULTURE</span><strong>Space to become more.</strong></div></div><div class="story-copy reveal">${tag('02 / THE CLUB. THE MINDSET.')}<h2>More than a gym.<br><em>Your daily reset.</em></h2><p>Daylight. Blue turf. Room to focus. A space that makes you want to put your phone down and put the work in.</p><p>Find us on the 7th floor of Ved-Vista Tower, N3 CIDCO. Come see the floor, meet the team, and make your next move.</p>${btn('Get to know Kulture','/about/','outline')}<div class="story-facts"><div><strong>07</strong><span>FLOORS ABOVE THE EVERYDAY</span></div><div><strong>N3</strong><span>RIGHT HERE IN CIDCO</span></div></div></div></div></section>
  <section class="wrap section club-preview"><div class="section-heading reveal"><div>${tag('03 / YOUR TRAINING GROUND')}<h2>The space.<br><em>The energy.</em></h2></div><p>A closer look at the actual club, from the strength floor to your next kilometre.</p></div><div class="club-photo-grid"><a class="club-photo large premium-reveal" href="/gallery/">${photo('club-floor.jpg','Actual gym floor, cardio equipment and blue training turf at Kulture')}<span>ROOM FOR YOUR NEXT CHAPTER.</span></a><a class="club-photo premium-reveal" href="/gallery/">${photo('free-weights.jpg','Actual free weights and strength racks at Kulture')}<span>BUILD YOUR FOUNDATION.</span></a><a class="club-photo premium-reveal" href="/gallery/">${photo('cardio-floor.jpg','Actual Bullrock treadmills at Kulture')}<span>FIND YOUR SECOND WIND.</span></a></div><div class="club-photo-footer"><span>PHOTOGRAPHED AT KULTURE FITNESS CLUB</span>${btn('Take a look inside','/gallery/','outline')}</div></section>
  <section class="review-band"><div class="wrap"><div class="review-rating reveal"><span class="review-score">5.0<span>/5</span></span><div><span class="stars">★★★★★</span><p>60 Google reviews</p></div></div><div class="reveal"><h2>A Kulture worth<br><em>coming back to.</em></h2><a class="text-link" href="${maps}" target="_blank" rel="noopener noreferrer">View the club on Google</a></div></div></section>
  <section class="wrap section"><div class="commitment-panel reveal"><div class="commitment-photo">${campaignPhoto('campaign-energy.webp','Athlete ready for a strength session')}<span class="image-credit">AI campaign</span></div><div class="commitment-copy">${tag('04 / COMMIT TO YOURSELF')}<h2>A month to begin.<br><em>A year to become.</em></h2><p>Start small or stay for the long run. Explore membership options and find a commitment that fits your life.</p><div class="duration-list"><span>01 MONTH</span><span>03 MONTHS</span><span>06 MONTHS</span><span>12 MONTHS</span></div>${btn('Find your membership','/memberships/')}</div></div></section>${cta()}`;

  const training = content.training;
  content.training = () => training().replace(/<div class="training-grid">[\s\S]*?<\/div><\/section>/, `${programs()}</section>`);
  const memberships = content.memberships;
  content.memberships = () => memberships().replace('<section class="page-intro wrap">','<section class="page-intro wrap campaign-intro">').replace('</h1><p class="intro-copy">', '</h1><p class="intro-copy">').replace('</p></section>', `</p><div class="intro-art">${campaignPhoto('campaign-detail.webp','Close detail of chalked hands on a barbell')}<span class="image-credit">AI campaign</span></div></section>`);
}
