export const initialContent={
  mock:true,
  plans:[{name:'Monthly',months:1,price:1800,joiningFee:500,inclusions:['Gym floor access','Strength & cardio equipment','General floor guidance']},{name:'Quarterly',months:3,price:4500,joiningFee:500,inclusions:['Gym floor access','Strength & cardio equipment','General floor guidance']},{name:'Half-yearly',months:6,price:8000,joiningFee:0,inclusions:['Gym floor access','Strength & cardio equipment','General floor guidance']},{name:'Annual',months:12,price:14000,joiningFee:0,inclusions:['Gym floor access','Strength & cardio equipment','General floor guidance']}],
  timings:{weekdays:'6:00 AM – 10:00 PM',saturday:'6:00 AM – 10:00 PM',sunday:'7:00 AM – 12:00 PM',closure:'Please confirm holiday timings with the front desk.'},
  trainers:[{name:'Arjun Deshmukh',role:'Strength & conditioning',qualification:'Trainer qualifications to be confirmed',availability:'Morning sessions',image:'strength-zone.jpg'},{name:'Sneha Patil',role:'Personal training & mobility',qualification:'Trainer qualifications to be confirmed',availability:'Evening sessions',image:'evening-training.jpg'}],
  services:[{name:'Strength training',description:'Free weights, racks, plate-loaded and cable machines.'},{name:'Cardio & conditioning',description:'Treadmills, endurance work, and functional movement.'},{name:'Personal training',description:'Individual coaching options. Enquire for availability and additional fees.'}],
  classes:[{name:'Mobility & movement',day:'Monday / Wednesday / Friday',time:'7:00 AM'},{name:'Functional conditioning',day:'Tuesday / Thursday / Saturday',time:'6:00 PM'}],
  policies:{trial:'Trial visits are subject to availability. The team confirms your date, timing, and any applicable trial fee before you visit.',refund:'Ask the team for the written refund and cancellation terms before purchasing a membership.',freeze:'Membership freeze and transfer requests are subject to the club’s confirmed policy. Contact the front desk before making a payment.'},
  gallery:[{image:'club-floor.jpg',title:'The training floor',category:'club'},{image:'cardio-floor.jpg',title:'Cardio with a view',category:'cardio'},{image:'strength-zone.jpg',title:'Strength starts here',category:'strength'},{image:'evening-training.jpg',title:'The evening Kulture',category:'strength'},{image:'free-weights.jpg',title:'Room to grow stronger',category:'strength'}],
  staffLabel:'Front desk',parking:'Call the front desk for parking guidance before your visit.',taxNote:'Mock prices shown in ₹. Applicable taxes and final charges must be confirmed by the gym. Personal training is priced separately.'
};
