import assert from 'node:assert/strict';
import worker from './worker.mjs';
import {openDatabase} from './local-db.mjs';
const DB=openDatabase(':memory:');const tasks=[];const env={DB,ASSETS:{fetch:async()=>new Response('asset')},PRIVATE_OWNER_BOOTSTRAP:'enabled'};const ctx={waitUntil:p=>tasks.push(p)};
const request=(path,method='GET',data,user,origin='http://local')=>worker.fetch(new Request('http://local'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{})},...(data?{body:JSON.stringify(data)}:{})}),env,ctx);
assert.equal((await request('/api/admin')).status,403);
assert.equal((await request('/api/admin','GET',null,'owner')).status,200);
assert.equal((await request('/api/admin','GET',null,'outsider')).status,403);
assert.equal((await request('/api/enquiries','POST',{},null,'http://other')).status,403);
const challenge=await (await request('/api/challenge')).json();const answer=(await DB.prepare('SELECT answer FROM challenges WHERE id = ?').bind(challenge.id).first()).answer;
const lead={id:crypto.randomUUID(),name:'Preview Test',phone:'0000000000',interest:'Trial visit',visitDate:'2027-01-01',visitTime:'08:00',message:'A test enquiry',challenge:challenge.id,answer,website:''};
assert.equal((await request('/api/enquiries','POST',{...lead,visitDate:'2020-01-01'})).status,400);
assert.equal((await request('/api/enquiries','POST',{...lead,answer:'999'})).status,400);
assert.equal((await request('/api/enquiries','POST',lead)).status,201);
assert.equal((await request('/api/enquiries','POST',lead)).status,200);
assert.equal((await DB.prepare('SELECT COUNT(*) AS count FROM leads').first()).count,1);
assert.equal((await request('/api/enquiries','POST',{...lead,id:crypto.randomUUID()})).status,400);
assert.equal((await request('/api/admin/lead','PATCH',{id:lead.id,status:'Trial Scheduled',notes:'Call completed',assignedTo:'Front desk'},'owner')).status,200);
assert.equal((await DB.prepare('SELECT status FROM leads WHERE id = ?').bind(lead.id).first()).status,'Trial Scheduled');
assert.equal((await request('/api/admin/staff','POST',{userId:'staff',name:'Front desk'},'owner')).status,200);
assert.equal((await request('/api/admin','GET',null,'staff')).status,200);
assert.equal((await request('/api/admin/content','PUT',{},'staff')).status,403);
assert.equal((await request('/api/admin/content','PUT',{},'owner')).status,400);
const current=await (await request('/api/content')).json();current.timings.weekdays='6:00 AM – 9:00 PM';assert.equal((await request('/api/admin/content','PUT',current,'owner')).status,200);
assert.equal((await (await request('/api/content')).json()).timings.weekdays,'6:00 AM – 9:00 PM');
assert.equal((await request('/api/admin/staff','DELETE',{userId:'staff'},'owner')).status,200);
assert.equal((await request('/api/admin','GET',null,'staff')).status,403);
await Promise.all(tasks);DB.close();console.log('Passed: saved trials, validation, idempotency, origin checks, owner/staff access, follow-ups, and persistent content edits.');
