import {initialContent} from './default-content.mjs';
const statuses=['New','Contacted','Trial Scheduled','Joined','Closed'];
const json=(value,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const sql=(env,s,...v)=>env.DB.prepare(s).bind(...v);
const clean=(x,max=100)=>typeof x==='string'?x.trim().slice(0,max):'';
const validDate=d=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return false;const date=new Date(d+'T00:00:00Z');return Number.isFinite(date.valueOf())&&date.toISOString().slice(0,10)===d;};
async function content(env){const row=await sql(env,'SELECT value FROM settings WHERE key = ?','content').first();return row?JSON.parse(row.value):structuredClone(initialContent);}
async function fingerprint(request){const ip=request.headers.get('cf-connecting-ip')||'local';const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(new Date().toISOString().slice(0,10)+':'+ip));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function admin(request,env){const user=request.headers.get('oai-authenticated-user-id');if(!user)return null;let owner=await sql(env,'SELECT value FROM settings WHERE key = ?','owner_id').first();if(!owner){if(env.PRIVATE_OWNER_BOOTSTRAP!=='enabled')return null;await sql(env,'INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)','owner_id',user).run();owner=await sql(env,'SELECT value FROM settings WHERE key = ?','owner_id').first();}if(owner.value===user)return {user,owner:true,email:request.headers.get('oai-authenticated-user-email')||'Owner'};const member=await sql(env,'SELECT name FROM staff WHERE user_id = ?',user).first();return member?{user,owner:false,email:member.name}:null;}
async function body(request){if(Number(request.headers.get('content-length')||0)>32768)throw Error('payload');let bytes=0;const reader=request.body?.getReader();if(!reader)throw Error('payload');const chunks=[];for(;;){const r=await reader.read();if(r.done)break;bytes+=r.value.byteLength;if(bytes>32768){await reader.cancel();throw Error('payload');}chunks.push(r.value);}const all=new Uint8Array(bytes);let offset=0;for(const c of chunks){all.set(c,offset);offset+=c.length;}return JSON.parse(new TextDecoder().decode(all));}
function validateContent(c){if(!c||typeof c.mock!=='boolean'||!Array.isArray(c.plans)||c.plans.length>8||!Array.isArray(c.trainers)||c.trainers.length>12||!Array.isArray(c.gallery)||c.gallery.length>30||!Array.isArray(c.classes)||c.classes.length>30||!Array.isArray(c.services)||c.services.length>20||!c.timings||!c.policies)return false;for(const p of c.plans)if(!clean(p.name)||!Number.isFinite(p.price)||p.price<0||p.price>1000000||!Number.isFinite(p.months)||p.months<1||p.months>60||!Number.isFinite(p.joiningFee)||p.joiningFee<0||!Array.isArray(p.inclusions))return false;for(const item of [...c.gallery,...c.trainers])if(!/^[a-zA-Z0-9._-]+\.(jpg|jpeg|png|webp)$/.test(item.image))return false;return JSON.stringify(c).length<30000;}
export default {async fetch(request,env,ctx){const url=new URL(request.url);const p=url.pathname;try{
 if(p.startsWith('/api/')&&!env.DB)return json({error:'Enquiries are temporarily unavailable. Please call the club.'},503);
 if(p.startsWith('/api/')&&request.method!=='GET'&&request.headers.get('origin')!==url.origin)return json({error:'This request is not allowed.'},403);
 if(p==='/api/content'&&request.method==='GET')return json(await content(env));
 if(p==='/api/challenge'&&request.method==='GET'){const now=Date.now(),network=await fingerprint(request);const count=await sql(env,'SELECT COUNT(*) AS count FROM challenges WHERE network = ? AND created_at > ?',network,now-600000).first();if(count.count>=20)return json({error:'Please wait a few minutes or call the club.'},429);const random=new Uint8Array(2);crypto.getRandomValues(random);const a=random[0]%8+2,b=random[1]%8+1,id=crypto.randomUUID();await sql(env,'INSERT INTO challenges (id,answer,expires_at,network,created_at) VALUES (?,?,?,?,?)',id,String(a+b),now+900000,network,now).run();return json({id,question:`What is ${a} + ${b}?`});}
 if(p==='/api/enquiries'&&request.method==='POST'){const data=await body(request);const id=clean(data.id,40);if(!/^[0-9a-f-]{36}$/.test(id))return json({error:'Please reload the form and try again.'},400);if(await sql(env,'SELECT id FROM leads WHERE id = ?',id).first())return json({id,status:'New'});const name=clean(data.name,80),phone=clean(data.phone,20),interest=clean(data.interest,80),date=clean(data.visitDate,10),time=clean(data.visitTime,5),message=clean(data.message,1000);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(!name||!/^[+0-9 ()-]{7,20}$/.test(phone)||!interest||!validDate(date)||date<today||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)||data.website)return json({error:'Check your details and choose a current or future visit date.'},400);const now=Date.now(),network=await fingerprint(request);const count=await sql(env,'SELECT COUNT(*) AS count FROM leads WHERE network = ? AND created_at > ?',network,now-3600000).first();if(count.count>=5)return json({error:'Too many enquiries. Please call the club to continue.'},429);const check=await sql(env,'DELETE FROM challenges WHERE id = ? AND answer = ? AND expires_at > ? AND network = ? RETURNING id',clean(data.challenge,40),clean(data.answer,10),now,network).first();if(!check)return json({error:'The quick check is incorrect or has expired. Please try again.'},400);const c=await content(env);await env.DB.batch([sql(env,'INSERT INTO leads (id,name,phone,interest,visit_date,visit_time,message,status,notes,assigned_to,created_at,updated_at,network) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',id,name,phone,interest,date,time,message,'New','',clean(c.staffLabel,80)||'Front desk',now,now,network),sql(env,'INSERT INTO metrics (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1','trial_requests')]);ctx.waitUntil(env.DB.batch([sql(env,'DELETE FROM challenges WHERE expires_at < ?',now),sql(env,"DELETE FROM leads WHERE status = 'Closed' AND updated_at < ?",now-90*86400000),sql(env,"UPDATE leads SET network = '' WHERE created_at < ?",now-86400000)]).catch(()=>console.error('Enquiry cleanup failed')));return json({id,status:'New'},201);}
 if(p==='/api/metrics'&&request.method==='POST'){const data=await body(request);if(!['call','whatsapp'].includes(data.event))return json({error:'Invalid event.'},400);await sql(env,'INSERT INTO metrics (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1',data.event).run();return json({ok:true});}
 if(p.startsWith('/api/admin')){const auth=await admin(request,env);if(!auth)return json({error:'Owner or authorised staff access is required.',userId:request.headers.get('oai-authenticated-user-id')||null},403);
  if(p==='/api/admin'&&request.method==='GET'){const leads=await sql(env,'SELECT id,name,phone,interest,visit_date,visit_time,message,status,notes,assigned_to,created_at,updated_at FROM leads ORDER BY created_at DESC LIMIT 1000').all();const metrics=await sql(env,'SELECT key,count FROM metrics').all();const staff=auth.owner?(await sql(env,'SELECT user_id,name FROM staff').all()).results:[];return json({auth,leads:leads.results,metrics:metrics.results,staff,content:auth.owner?await content(env):null});}
  if(p==='/api/admin/lead'&&request.method==='PATCH'){const data=await body(request);if(!statuses.includes(data.status))return json({error:'Invalid status.'},400);const r=await sql(env,'UPDATE leads SET status = ?,notes = ?,assigned_to = ?,updated_at = ? WHERE id = ?',data.status,clean(data.notes,2000),clean(data.assignedTo,80),Date.now(),clean(data.id,40)).run();return r.meta.changes?json({ok:true}):json({error:'Enquiry not found.'},404);}
  if(!auth.owner)return json({error:'Only the owner can manage content and staff.'},403);
  if(p==='/api/admin/content'&&request.method==='PUT'){const data=await body(request);if(!validateContent(data))return json({error:'Please check the content fields and image filenames.'},400);await sql(env,'INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','content',JSON.stringify(data)).run();return json({ok:true});}
  if(p==='/api/admin/staff'&&request.method==='POST'){const data=await body(request);if(!clean(data.userId,200)||!clean(data.name,80))return json({error:'Name and Site user ID are required.'},400);await sql(env,'INSERT INTO staff (user_id,name) VALUES (?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name',clean(data.userId,200),clean(data.name,80)).run();return json({ok:true});}
  if(p==='/api/admin/staff'&&request.method==='DELETE'){const data=await body(request);await sql(env,'DELETE FROM staff WHERE user_id = ?',clean(data.userId,200)).run();return json({ok:true});}
 }
 if(p.startsWith('/api/'))return json({error:'Not found.'},404);
 if(p.startsWith('/admin')){if(!request.headers.get('oai-authenticated-user-id'))return Response.redirect(url.origin+'/signin-with-chatgpt?return_to=%2Fadmin%2F',302);}
 const response=await env.ASSETS.fetch(request);const secure=new Response(response.body,response);secure.headers.set('X-Content-Type-Options','nosniff');secure.headers.set('Referrer-Policy','strict-origin-when-cross-origin');secure.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com; base-uri 'self'; form-action 'self'");return secure;
 }catch(error){console.error('Kulture request failed',{path:p,type:error?.message==='payload'?'invalid-input':'storage'});return json({error:error?.message==='payload'?'Please check your enquiry and try again.':'Something went wrong. Your request was not confirmed. Please try again or call the club.'},error?.message==='payload'?400:503);}}};


